# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ef36dfa5c7b673e4421b6e56b20fe054cbbc4e75cb963ad61917d04f3e31b0f8f270f6e26f52b392e4205ce25e9a03c5e2edad4ceeae37b5fa50c385c45df4e

test:
  secret_key_base: 6b1c9e4d0fc4ec81ab9c58fa8ac7f10a68c68641a7e606b9720a82ecea6e37e16b86381f412af08f2e507255463d8c3726db8abcd4ec50e1a12a4d8d982e310c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
